### ISSUE TITLE
Case issue when building from GNU/Linux

### ISSUE THREAD

**Issue by Ace17** [sonoro1234/luaRtAudio#1]
Seems like the git submodule is named "rtaudioORIG", but cmake thinks it's named "RtAudioORIG".

$ git clone https://github.com/sonoro1234/luaRtAudio.git && cd luaRtAudio && cmake .
Cloning into 'luaRtAudio'...
remote: Reusing existing pack: 164, done.
remote: Counting objects: 13, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 177 (delta 2), reused 0 (delta 0)
Receiving objects: 100% (177/177), 1.09 MiB | 776.00 KiB/s, done.
Resolving deltas: 100% (54/54), done.
Checking connectivity... done.
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at CMakeLists.txt:23 (add_subdirectory):
  add_subdirectory given source "RtAudioORIG" which is not an existing
  directory.

CMake Error at CMakeLists.txt:26 (get_directory_property):
  get_directory_property DIRECTORY argument provided but requested directory
  not found.  This could be because the directory argument was invalid or, it
  is valid but has not been processed yet.

CMake Error at CMakeLists.txt:41 (INSTALL):
  install FILES given no DESTINATION!

-- Configuring incomplete, errors occurred!
See also "/tmp/luaRtAudio/CMakeFiles/CMakeOutput.log".

**Comment by sonoro1234** [comment]
RtAudioORIG is a submodule pointing to the original RtAudio github.
You should use submodule update to get it in your hard disk
(After that you could check if it is present that folder)

victor bombi

**Comment by Ace17** [comment]
Thanks for the information.
But please keep in mind the filesystem is case-sensitive on GNU/Linux.
The submodule gets cloned to "rtaudioORIG", but the CMakeLists file refer to "RtAudioORIG".

**Comment by sonoro1234** [comment]
fixed.

**Comment by Ace17** [comment]
```
ace@ANTEC /tmp % git clone https://github.com/sonoro1234/luaRtAudio.git
Cloning into 'luaRtAudio'...
cd luaremote: Reusing existing pack: 164, done.
remote: Counting objects: 17, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 181 (delta 3), reused 0 (delta 0)
Receiving objects: 100% (181/181), 1.09 MiB | 654.00 KiB/s, done.
Resolving deltas: 100% (55/55), done.
Checking connectivity... done.

ace@ANTEC /tmp % cd luaRtAudio

ace@ANTEC luaRtAudio % ls
build/  CMakeLists.txt  luaRtAudio/  README.md  rtaudioORIG/  samples/

ace@ANTEC luaRtAudio % git submodule init
Submodule 'rtaudioORIG' (https://github.com/thestk/rtaudio.git) registered for path 'rtaudioORIG'

ace@ANTEC luaRtAudio % git submodule update 
Cloning into 'rtaudioORIG'...
remote: Reusing existing pack: 1528, done.
remote: Total 1528 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (1528/1528), 1.35 MiB | 1011.00 KiB/s, done.
Resolving deltas: 100% (1076/1076), done.
Checking connectivity... done.
Submodule path 'rtaudioORIG': checked out 'c0b9de42a3e7f7c168380c9e91c5993524a11154'

ace@ANTEC luaRtAudio % cmake . 
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for gettimeofday
-- Looking for gettimeofday - found
-- Using Linux PulseAudio
-- Found ALSA: /usr/lib/x86_64-linux-gnu/libasound.so (found version "1.0.27.2") 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Using Linux ALSA
-- Using JACK
CMake Error at CMakeLists.txt:41 (INSTALL):
  install FILES given no DESTINATION!


-- Configuring incomplete, errors occurred!
See also "/tmp/luaRtAudio/CMakeFiles/CMakeOutput.log".
See also "/tmp/luaRtAudio/CMakeFiles/CMakeError.log".

```

**Comment by sonoro1234** [comment]
did you set all variables in toolchain.cmake?
specifically INSTALL_LMOD where *.lua files should go?

**Comment by Ace17** [comment]
I'd prefer these libraries to be autodetected.
You can achieve it this way:

```
PROJECT(luaRtAudio)
cmake_minimum_required(VERSION 2.8)

find_package(Lua51 REQUIRED)
add_definitions(-DLUA_LIB)

find_path(SNDFILE_INCLUDE_DIR sndfile.h REQUIRED)
find_library(SNDFILE_LIBRARY NAMES sndfile sndfile-1)

#first take care of RtAudio CMake
if (WIN32)
    set(AUDIO_WINDOWS_DS ON CACHE INTERNAL "use windows ds!")
    set(AUDIO_WINDOWS_ASIO ON CACHE INTERNAL "use windows asio!")
    set(AUDIO_WINDOWS_WASAPI ON CACHE INTERNAL "use windows wasapi!")
endif(WIN32)

if (APPLE)
    set(AUDIO_OSX_CORE ON CACHE INTERNAL "use OSX_CORE!")
endif (APPLE)

if (UNIX AND NOT APPLE)
    set(AUDIO_LINUX_OSS ON CACHE INTERNAL "AUDIO_LINUX_OSS!")
    set(AUDIO_LINUX_ALSA ON CACHE INTERNAL "AUDIO_LINUX_ALSA!")
    set(AUDIO_LINUX_PULSE ON CACHE INTERNAL "AUDIO_LINUX_PULSE!")
    set(AUDIO_UNIX_JACK ON CACHE INTERNAL "AUDIO_UNIX_JACK!")
endif ()

set(BUILD_TESTING OFF CACHE INTERNAL "dont build tests!")
add_subdirectory(rtaudioORIG)

#now luaRtAudio
get_directory_property(LINKLIBS DIRECTORY rtaudioORIG DEFINITION LINKLIBS)
if(SNDFILE_INCLUDE_DIR)
    add_definitions(-DUSE_SNDFILE)
endif()
INCLUDE_DIRECTORIES(${LUA_INCLUDE_DIR})
INCLUDE_DIRECTORIES(rtaudioORIG)
ADD_LIBRARY(luaRtAudio SHARED luaRtAudio/luaRtAudio.cpp)
set_target_properties(luaRtAudio PROPERTIES PREFIX "" OUTPUT_NAME core)

TARGET_LINK_LIBRARIES(luaRtAudio ${LUA_LIBRARY} rtaudio_static ${LINKLIBS})

install(TARGETS luaRtAudio DESTINATION ${INSTALL_CMOD}/RtAudio)
#INSTALL(FILES luaRtAudio/RtAudio.lua DESTINATION ${INSTALL_LMOD})
INSTALL (FILES ${LINKSNDFILE} DESTINATION ${INSTALL_CMOD})
```

**Comment by sonoro1234** [comment]
find_package(Lua51 REQUIRED)
is not working for me as it depends in LUA_DIR ENV variable being set by any of the many lua distributions but I dont use any of them :-(

find_path(SNDFILE_INCLUDE_DIR sndfile.h REQUIRED)
find_library(SNDFILE_LIBRARY NAMES sndfile sndfile-1)
is even worse as I should provide a HINT about where to search

**Comment by sonoro1234** [comment]
Perhaps this automatic finding code could be included in toolchain.cmake as an alternative to provide hardcoded paths

**Comment by sonoro1234** [comment]
CMake modified
