### ISSUE TITLE
Can't analyze microphone input

### ISSUE THREAD

**Issue by luastoned** [sonoro1234/luaRtAudio#2]
Hey, line #318 in the current luaRtAudio.cpp (memset) prevents any input analysis.
Maybe add a different callback that allows for proper input handling instead of just looping it to the output?

Cheers

**Comment by sonoro1234** [comment]
I am glad someone is using this. 
Would like to now your SO.
Just corrected the issue and comitted.

Best
victor

**Comment by luastoned** [comment]
Thanks for the quick fix.
Do you think there could be a callback that does not duplicate the input to the output?
I would argue that for debugging purposes it is quite nice (to hear the microphone working) but having to return a table with zero values to not hear the input on the output line seems kind of odd.

What exactly do you mean by 'SO'?

**Comment by sonoro1234** [comment]
I am not sure to understand:

RtAudio has only one callback for stream.
I have setted two kind of callbacks: one for plain lua the other for luajiit.
Then in each callback I perform four tasks
1- call lua callback (with input added to out) before playing audio files. Here we can have generators or input analizing
2- play audio files (add them to out)
3- call lua callback after playing audio files. Here we can do post processing of audio files output.
4- writing out to file if recorfile is given

which would be the proposal in this framework?

By SO I meant operative system (win32-64,linux,mac) as I dont have any information from other people I dont know where luaRTAudio is working and compiling OK.

best
victor

**Comment by luastoned** [comment]
I would say that returning false (instead of nil/a table) at the first step (1) should prevent the input from being written to the output. This way  people don't need to return a table with a bunch of zero values to analyze the microphone but don't play it back.

I am on Win7 64, VS10/12.
I had to change line #255 to double *BUFFER = new double[nFrames*channels]; since MSVC will throw an error with the current declaration. Of cource free() needs to be called on the return points.

**Comment by sonoro1234** [comment]
I have made changes in order to zero outputbuffer if you return false in a non-ffi pre(1) or post(3) callback
In ffi callbacks (pre or post) you are responsible of zeroing the buffer

**Comment by luastoned** [comment]
The current first callback still has no input data (I guess you can only write generators there) but aside from that it's looking good.

Here's what I've been able to produce so far (luaRtAudio, libfada w/ FFI, OpenGL w/ FFI)
![LuaJIT](http://img.luastoned.com/lav_v2.png)

Cheers

**Comment by sonoro1234** [comment]
Yes I would have to push the output buffer as argument in the first nonffi callback (as happens in the first ffi callback) but I dont know if it is necessary as it would have a CPU cost...

> Here's what I've been able to produce so far (luaRtAudio, libfada w/ FFI, OpenGL w/ FFI)
> luajit ffi is great but lualanes is also doing a great job here...
